// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: Todo.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Todo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Owner string `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Date  string `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *Todo) Reset() {
	*x = Todo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Todo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_Todo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_Todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Todo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Todo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Todo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type TodoFull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Todo *Todo  `protobuf:"bytes,2,opt,name=Todo,proto3" json:"Todo,omitempty"`
}

func (x *TodoFull) Reset() {
	*x = TodoFull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Todo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoFull) ProtoMessage() {}

func (x *TodoFull) ProtoReflect() protoreflect.Message {
	mi := &file_Todo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoFull.ProtoReflect.Descriptor instead.
func (*TodoFull) Descriptor() ([]byte, []int) {
	return file_Todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoFull) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoFull) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

var File_Todo_proto protoreflect.FileDescriptor

var file_Todo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x54, 0x6f, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x58, 0x0a, 0x04, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x0a, 0x08,
	0x54, 0x6f, 0x64, 0x6f, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x54, 0x6f, 0x64, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x6f,
	0x64, 0x6f, 0x52, 0x04, 0x54, 0x6f, 0x64, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Todo_proto_rawDescOnce sync.Once
	file_Todo_proto_rawDescData = file_Todo_proto_rawDesc
)

func file_Todo_proto_rawDescGZIP() []byte {
	file_Todo_proto_rawDescOnce.Do(func() {
		file_Todo_proto_rawDescData = protoimpl.X.CompressGZIP(file_Todo_proto_rawDescData)
	})
	return file_Todo_proto_rawDescData
}

var file_Todo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Todo_proto_goTypes = []interface{}{
	(*Todo)(nil),     // 0: main.Todo
	(*TodoFull)(nil), // 1: main.TodoFull
}
var file_Todo_proto_depIdxs = []int32{
	0, // 0: main.TodoFull.Todo:type_name -> main.Todo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Todo_proto_init() }
func file_Todo_proto_init() {
	if File_Todo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Todo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Todo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Todo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoFull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Todo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Todo_proto_goTypes,
		DependencyIndexes: file_Todo_proto_depIdxs,
		MessageInfos:      file_Todo_proto_msgTypes,
	}.Build()
	File_Todo_proto = out.File
	file_Todo_proto_rawDesc = nil
	file_Todo_proto_goTypes = nil
	file_Todo_proto_depIdxs = nil
}
